### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by NaokiSakaiRose** [NaokiSakaiRose/chat-space#8]
#IPアドレス
18.177.66.95

**Comment by miyu-yamamoto** [comment]
酒井原さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**①追加↓メンバーの表示カラーを見本と揃えましょう
②投稿されたメッセージの表示を見本と揃えましょう
③テキストを入力する欄の青枠の範囲を見本と揃えましょう**
<img width="989" alt="スクリーンショット 2020-05-29 10 41 43" src="https://user-images.githubusercontent.com/59544869/83211960-58cb2d00-a199-11ea-9c45-e695d843b852.png">

**↓こちらが見本です**
<img width="1426" alt="スクリーンショット 2020-05-29 10 46 19" src="https://user-images.githubusercontent.com/59544869/83212094-a9428a80-a199-11ea-8d6c-d6d6e0ffdf3a.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by NaokiSakaiRose** [comment]
修正いたしました。再度、ご確認のほどお願いいたします。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by NaokiSakaiRose** [comment]
ご確認ありがとうございました。
